export type Item = {
  id: number;
  name: string;
  price: number;
  originalPrice: number;
  description: string;
  categoryKey: string;
  subcategory: string;
  ingredients: string[];
  imageUrl: string;
  addOns: { name: string; price: number }[]; // New: Add-ons for each item
};

export const items: Item[] = [
  // Breakfast
  {
    id: 1,
    name: "French Croissant",
    price: 6.5,
    originalPrice: 8.0,
    description: "Buttery, flaky pastry baked fresh daily with premium French butter",
    categoryKey: "breakfast",
    subcategory: "Continental",
    ingredients: ["Flour", "Butter", "Yeast", "Salt"],
    imageUrl: "https://images.pexels.com/photos/3892469/pexels-photo-3892469.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Extra Butter", price: 1.0 },
      { name: "Jam", price: 1.5 },
      { name: "Nutella", price: 2.0 },
    ],
  },
  {
    id: 2,
    name: "Belgian Pancakes",
    price: 14.5,
    originalPrice: 16.0,
    description: "Light and fluffy pancakes served with maple syrup and fresh berries",
    categoryKey: "breakfast",
    subcategory: "American",
    ingredients: ["Flour", "Eggs", "Milk", "Maple Syrup", "Berries"],
    imageUrl: "https://images.pexels.com/photos/14335957/pexels-photo-14335957.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Whipped Cream", price: 1.5 },
      { name: "Extra Berries", price: 2.0 },
      { name: "Chocolate Sauce", price: 1.5 },
    ],
  },
  {
    id: 3,
    name: "Truffle Eggs Benedict",
    price: 19.5,
    originalPrice: 22.0,
    description: "Poached eggs on toasted brioche with hollandaise and truffle oil",
    categoryKey: "breakfast",
    subcategory: "Continental",
    ingredients: ["Eggs", "Brioche", "Hollandaise", "Truffle Oil", "Ham"],
    imageUrl: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Extra Hollandaise", price: 2.0 },
      { name: "Smoked Salmon", price: 3.5 },
      { name: "Avocado", price: 2.5 },
    ],
  },
  {
    id: 4,
    name: "Artisan Waffle",
    price: 13.5,
    originalPrice: 15.0,
    description: "Crispy Belgian waffle with seasonal fruit and whipped cream",
    categoryKey: "breakfast",
    subcategory: "American",
    ingredients: ["Flour", "Eggs", "Butter", "Fruit", "Whipped Cream"],
    imageUrl: "https://images.unsplash.com/photo-1572448804125-7f1e3b9fc9e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1260&h=750&q=80",
    addOns: [
      { name: "Caramel Sauce", price: 1.5 },
      { name: "Ice Cream Scoop", price: 2.0 },
      { name: "Nuts", price: 1.0 },
    ],
  },
  {
    id: 5,
    name: "Avocado Toast Deluxe",
    price: 12.0,
    originalPrice: 14.0,
    description: "Sourdough bread topped with smashed avocado, feta, and microgreens",
    categoryKey: "breakfast",
    subcategory: "Healthy Options",
    ingredients: ["Avocado", "Sourdough", "Feta", "Microgreens", "Lemon"],
    imageUrl: "https://images.pexels.com/photos/4062617/pexels-photo-4062617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Poached Egg", price: 2.0 },
      { name: "Chili Flakes", price: 0.5 },
      { name: "Cherry Tomatoes", price: 1.5 },
    ],
  },
  {
    id: 6,
    name: "Full English Breakfast",
    price: 16.5,
    originalPrice: 18.0,
    description: "Traditional breakfast with eggs, bacon, sausage, beans, and toast",
    categoryKey: "breakfast",
    subcategory: "American",
    ingredients: ["Eggs", "Bacon", "Sausage", "Beans", "Toast"],
    imageUrl: "https://images.pexels.com/photos/19552394/pexels-photo-19552394.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Extra Bacon", price: 2.5 },
      { name: "Mushrooms", price: 1.5 },
      { name: "Grilled Tomato", price: 1.0 },
    ],
  },
  // Lunch
  {
    id: 7,
    name: "Caesar Salad",
    price: 10.5,
    originalPrice: 12.0,
    description: "Crisp romaine with Caesar dressing, croutons, and parmesan",
    categoryKey: "lunch",
    subcategory: "Salads",
    ingredients: ["Romaine", "Caesar Dressing", "Croutons", "Parmesan"],
    imageUrl: "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Grilled Chicken", price: 3.0 },
      { name: "Extra Parmesan", price: 1.0 },
      { name: "Anchovies", price: 1.5 },
    ],
  },
  {
    id: 8,
    name: "Turkey Club Sandwich",
    price: 12.5,
    originalPrice: 14.0,
    description: "Toasted sandwich with turkey, bacon, lettuce, and mayo",
    categoryKey: "lunch",
    subcategory: "Sandwiches",
    ingredients: ["Turkey", "Bacon", "Lettuce", "Tomato", "Mayo"],
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1260&h=750&q=80",
    addOns: [
      { name: "Extra Bacon", price: 2.0 },
      { name: "Avocado", price: 2.0 },
      { name: "Cheddar Cheese", price: 1.5 },
    ],
  },
  {
    id: 9,
    name: "Tomato Basil Soup",
    price: 8.0,
    originalPrice: 9.5,
    description: "Creamy tomato soup with fresh basil and croutons",
    categoryKey: "lunch",
    subcategory: "Soups",
    ingredients: ["Tomatoes", "Basil", "Cream", "Croutons"],
    imageUrl: "https://images.pexels.com/photos/1279331/pexels-photo-1279331.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Garlic Bread", price: 2.0 },
      { name: "Extra Croutons", price: 0.5 },
      { name: "Parmesan", price: 1.0 },
    ],
  },
  // Dinner
  {
    id: 10,
    name: "Grilled Ribeye Steak",
    price: 28.0,
    originalPrice: 32.0,
    description: "Juicy ribeye steak with herb butter and roasted vegetables",
    categoryKey: "dinner",
    subcategory: "Steaks",
    ingredients: ["Ribeye", "Herb Butter", "Vegetables"],
    imageUrl: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?ixlib=rb-4.0.3&auto=format&fit=crop&w=1260&h=750&q=80",
    addOns: [
      { name: "Truffle Sauce", price: 3.0 },
      { name: "Mashed Potatoes", price: 2.5 },
      { name: "Peppercorn Sauce", price: 2.0 },
    ],
  },
  {
    id: 11,
    name: "Pan-Seared Salmon",
    price: 24.0,
    originalPrice: 27.0,
    description: "Fresh salmon with lemon herb sauce and asparagus",
    categoryKey: "dinner",
    subcategory: "Seafood",
    ingredients: ["Salmon", "Lemon", "Herbs", "Asparagus"],
    imageUrl: "https://images.pexels.com/photos/555775/pexels-photo-555775.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Lemon Butter Sauce", price: 2.0 },
      { name: "Quinoa Side", price: 2.5 },
      { name: "Extra Asparagus", price: 1.5 },
    ],
  },
  {
    id: 12,
    name: "Mushroom Risotto",
    price: 18.5,
    originalPrice: 21.0,
    description: "Creamy risotto with wild mushrooms and parmesan",
    categoryKey: "dinner",
    subcategory: "Pasta",
    ingredients: ["Rice", "Mushrooms", "Parmesan", "Broth"],
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1260&h=750&q=80",
    addOns: [
      { name: "Truffle Oil", price: 2.5 },
      { name: "Grilled Chicken", price: 3.0 },
      { name: "Extra Parmesan", price: 1.0 },
    ],
  },
  // Starters
  {
    id: 13,
    name: "Bruschetta",
    price: 7.5,
    originalPrice: 9.0,
    description: "Toasted bread with tomato, basil, and balsamic glaze",
    categoryKey: "starters",
    subcategory: "Cold Appetizers",
    ingredients: ["Bread", "Tomato", "Basil", "Balsamic"],
    imageUrl: "https://images.unsplash.com/photo-1559314809-0f31657def5e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1260&h=750&q=80",
    addOns: [
      { name: "Extra Balsamic", price: 1.0 },
      { name: "Mozzarella", price: 1.5 },
      { name: "Prosciutto", price: 2.0 },
    ],
  },
  {
    id: 14,
    name: "Calamari Fritti",
    price: 9.5,
    originalPrice: 11.0,
    description: "Crispy fried calamari with marinara sauce",
    categoryKey: "starters",
    subcategory: "Hot Appetizers",
    ingredients: ["Calamari", "Flour", "Marinara"],
    imageUrl: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Spicy Marinara", price: 1.0 },
      { name: "Lemon Aioli", price: 1.5 },
      { name: "Extra Calamari", price: 2.0 },
    ],
  },
  // Desserts
  {
    id: 15,
    name: "Chocolate Lava Cake",
    price: 8.0,
    originalPrice: 9.5,
    description: "Warm chocolate cake with a molten center and vanilla ice cream",
    categoryKey: "desserts",
    subcategory: "Cakes",
    ingredients: ["Chocolate", "Flour", "Eggs", "Ice Cream"],
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-4.0.3&auto=format&fit=crop&w=1260&h=750&q=80",
    addOns: [
      { name: "Extra Ice Cream", price: 2.0 },
      { name: "Berry Compote", price: 1.5 },
      { name: "Whipped Cream", price: 1.0 },
    ],
  },
  {
    id: 16,
    name: "Crème Brûlée",
    price: 7.5,
    originalPrice: 8.5,
    description: "Classic vanilla custard with caramelized sugar top",
    categoryKey: "desserts",
    subcategory: "French Pastries",
    ingredients: ["Vanilla Custard", "Sugar"],
    imageUrl: "https://images.pexels.com/photos/633501/pexels-photo-633501.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Fresh Berries", price: 1.5 },
      { name: "Caramel Sauce", price: 1.0 },
      { name: "Mint Garnish", price: 0.5 },
    ],
  },
  // Drinks
  {
    id: 17,
    name: "Espresso",
    price: 4.0,
    originalPrice: 5.0,
    description: "Rich, bold espresso made with premium beans",
    categoryKey: "drinks",
    subcategory: "Coffee",
    ingredients: ["Coffee Beans", "Water"],
    imageUrl: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    addOns: [
      { name: "Extra Shot", price: 1.5 },
      { name: "Whipped Cream", price: 1.0 },
      { name: "Caramel Syrup", price: 0.5 },
    ],
  },
  {
    id: 18,
    name: "Fresh Orange Juice",
    price: 5.5,
    originalPrice: 6.5,
    description: "Freshly squeezed orange juice, served chilled",
    categoryKey: "drinks",
    subcategory: "Fresh Juices",
    ingredients: ["Oranges"],
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-4.0.3&auto=format&fit=crop&w=1260&h=750&q=80",
    addOns: [
      { name: "Mint Leaves", price: 0.5 },
      { name: "Ginger Shot", price: 1.0 },
      { name: "Sparkling Water", price: 1.5 },
    ],
  },
];